// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA1-Xyz54c7QdfIZP6_mqt6GGk7CN4Mcg',
    appId: '1:114199149182:web:6a4516ae55ec0e35ab362f',
    messagingSenderId: '114199149182',
    projectId: 'coinone-9273c',
    authDomain: 'coinone-9273c.firebaseapp.com',
    storageBucket: 'coinone-9273c.appspot.com',
    measurementId: 'G-H3EQYKSHSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcxLvF1NAY6B9brjgb9X3zIUGKWyAiNzg',
    appId: '1:114199149182:android:052240bbd051f672ab362f',
    messagingSenderId: '114199149182',
    projectId: 'coinone-9273c',
    storageBucket: 'coinone-9273c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwoCuX1hNYW8qXhEjSi0SnGd8JE6I-rMY',
    appId: '1:114199149182:ios:f78dad4190012ce4ab362f',
    messagingSenderId: '114199149182',
    projectId: 'coinone-9273c',
    storageBucket: 'coinone-9273c.appspot.com',
    iosBundleId: 'com.example.coinoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwoCuX1hNYW8qXhEjSi0SnGd8JE6I-rMY',
    appId: '1:114199149182:ios:f78dad4190012ce4ab362f',
    messagingSenderId: '114199149182',
    projectId: 'coinone-9273c',
    storageBucket: 'coinone-9273c.appspot.com',
    iosBundleId: 'com.example.coinoneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA1-Xyz54c7QdfIZP6_mqt6GGk7CN4Mcg',
    appId: '1:114199149182:web:bdf3d613d5459fa4ab362f',
    messagingSenderId: '114199149182',
    projectId: 'coinone-9273c',
    authDomain: 'coinone-9273c.firebaseapp.com',
    storageBucket: 'coinone-9273c.appspot.com',
    measurementId: 'G-WJW1EBZZZB',
  );
}
